### ISSUE TITLE
Difficult to find the PS ID for visualization

### ISSUE THREAD

**Issue by pbrotoisworo** [kenquix/ps-insar_snap-stamps_visualizer#1]
Hi @kenquix. This is a really great app. I was actually thinking of making something like this but you already created something that works pretty well.

When I'm using the webapp I'm not sure how to find the ID number of the location I want to visualize. While I can select the PS in the dropdown in the sidebar. It's really hard to select the location I want to visualize.

I looked around in the code and I think this is the code for the PS tooltip in the webmap:

https://github.com/kenquix/ps-insar_snap-stamps_visualizer/blob/1adc42b8e86cf8290c6e37dbc9cfe827b7bccd25/app.py#L86

Maybe it can be revised to show the PS ID also? Something like:
```python
hovertemplate='%{ps}: %{displacement} mm'
```

**Comment by kenquix** [comment]
Already incorporated your suggestion @pbrotoisworo. Thanks!
