### ISSUE TITLE
Colors for web map does not match plot

### ISSUE THREAD

**Issue by pbrotoisworo** [kenquix/ps-insar_snap-stamps_visualizer#2]
Hello,

I think the color bar for the web map is flipped.

For context, my analysis shows Southern Iceland from August 2019 - August 2020. I've selected a PS within [Fragradalsfjall volcano](https://www.volcanodiscovery.com/fagradalsfjall.html) that was about to erupt in Iceland. In the plot you can see positive displacement but in the webmap it shows negative displacement.

I drew a square around the selected PS.

![image](https://user-images.githubusercontent.com/32087633/124617511-91176180-dea9-11eb-8d3c-0c60431cd10f.png)

**Comment by kenquix** [comment]
The map you shared shows the displacements for the date 2019-09-14 which from the chart is negative for the selected PS. You can use the slider to select the current date. As for the selected PS, color is changed to highlight but I agree it is misleading, will just change the size of the marker, not the color.

**Comment by pbrotoisworo** [comment]
Oh I see, I just misunderstood the UI. A suggestion I have is to let the user know that the map and the plot have separate controls on the sidebar to minimize confusion.

**Comment by kenquix** [comment]
I've pushed some changes to the layout of the app. Let me know what you think about it.

**Comment by pbrotoisworo** [comment]
I think the new update is improved in terms of usability but I'm not sure what's the purpose of this number input. I don't see anything change when I update the number input. Maybe you can add tooltips to fully explain the inputs? In my experience in the when reading the SNAP forums people can easily get confused or they overlook small details.

![image](https://user-images.githubusercontent.com/32087633/124766499-8fad6e00-df69-11eb-800e-2033e2c0fd1b.png)

**Comment by kenquix** [comment]
That's supposed to control the maximum number of points that can be plotted. Changed the behavior to accept only values 10,000 points and above. Also added some tooltips for the widgets. Thanks for the feedback.

**Comment by pbrotoisworo** [comment]
I think it's more understandable. I'll close this issue.
